spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/flowpay
spring.datasource.username=flowpay_user
spring.datasource.password=flowpay_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=flowpay_user
spring.rabbitmq.password=flowpay_password
